# macOS specific settings. Required by ~/.config/kitty/macos-launch-services-cmdline
font_size 14.0
background_opacity 0.88
kitty_mod cmd
macos_traditional_fullscreen yes
macos_titlebar_color system
macos_quit_when_last_window_closed yes

# hit ESC then automatically change IM to Alphabet mode
map escape combine : send_text all \x1b : launch --type=background im-select com.google.inputmethod.Japanese.Roman
