# Linux specific settings. Required by ~/.local/share/applications/kitty.desktop
font_size 14.0
background_opacity 0.85
#wayland_titlebar_color system

map ctrl+shift+f toggle_maximized
map ctrl+backspace send_key escape

# hit ESC then automatically change IM to Alphabet mode
map escape combine : send_text all \x1b : launch --type=background fcitx5-remote -c
map ctrl+backspace combine : send_text all \x1b : launch --type=background fcitx5-remote -c

# copy mode for GPD
map ctrl+q>backspace launch --type=overlay --env PATH="$HOME/.local/bin:$PATH" --stdin-source=@screen_scrollback nvim --cmd 'let g:lazyvim_no_ui = 1' -c 'set readonly nomodifiable buftype=nofile bufhidden=wipe nornu nonumber signcolumn=no wrap clipboard=unnamedplus | nnoremap q :q!<CR>' -c 'syntax on' -c 'autocmd VimEnter * setlocal modifiable | %s/^\S.*\] \(.\{-}\)\s\{2,}\[.*\]$/\% \1/e | %s/^\S.*\]\s*$/\% /e | setlocal nomodifiable | runtime! syntax/zsh.vim | syntax match TermPrompt /^% / containedin=ALL | highlight! TermPrompt ctermfg=yellow guifg=yellow' -c 'normal! G' -c 'call feedkeys("ll")' -

# for debug
#map f1 show_kitty_env_vars
